---
- name: Carregando pacotes instalados como facts.
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.userspace_bits == '32'

- name: Atualizando libseccomp2 para a versão mais recente (32-bit Debian).
  ansible.builtin.import_tasks: tasks/debian-libseccomp-update.yml
  when:
    - ansible_facts.os_family == "Debian"
    - ansible_facts.userspace_bits == '32'
    - ansible_facts.packages['libseccomp2'][0]['version'] is version('2.4.4', '<')

- name: Sincronizando diretório internet-monitoring
  ansible.posix.synchronize:
    src: files/internet-monitoring
    dest: "{{ config_dir }}/"
    delete: false
    recursive: true
    perms: false
  become: false

- name: Certifique-se de que o diretório de monitoramento da Internet não seja um repositório Git.
  ansible.builtin.file:
    path: "{{ config_dir }}/internet-monitoring/.git/"
    state: absent
  become: false

- name: Copiando templates de internet-monitoring
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/internet-monitoring/{{ item.dest }}"
    mode: 0644
  loop:
    - src: docker-compose.yml.j2
      dest: docker-compose.yml
    - src: grafana-config.monitoring.j2
      dest: grafana/config.monitoring
    - src: prometheus.yml.j2
      dest: prometheus/prometheus.yml
    - src: prometheus-pinghosts.yaml.j2
      dest: prometheus/pinghosts.yaml
  notify: Restart internet-monitoring
  become: false

- name: Certifique-se de que internet-monitoring esteja em execução.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/internet-monitoring/"
    build: false
  become: false