---
name: ansible-lint
on:
  push:
    branches:
      - main
jobs:
  ansible_lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6

  discord_message:
    name: Discord Message
    runs-on: ubuntu-latest
    needs: ansible_lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine Status
        id: determine_status
        run: echo "::set-output name=status::${{ job.status }}"

      - name: Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
            severity: info
            details: Succeeded!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        
      - name: Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Failed!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        
      - name: Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
            severity: warn
            details: Cancelled!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Error
        uses: rjstone/discord-webhook-notify@v1
        if: error()
        with:
            severity: warn
            details: Error!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}