---
name: ansible-lint
on: 
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - '*'
      - '!main'
jobs:
  build_ansible_lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Instalando dependencias
        id: ansible-lint-install
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible-lint
      - name: Executando Lint
        id: ansible-lint-execute
        run: |
          ansible-lint

      - name: Discord Message
        uses: th0th/notify-discord@v0.4.1
        if: ${{ always() }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: "Build and deploy"
          GITHUB_JOB_STATUS: ${{ job.status }}

#    needs: build_ansible_lint